
package IU;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Desktop;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

import javax.swing.JPanel;

import org.json.simple.JSONArray;

import LOGICA.Stack;

/**
 *
 * @author delog
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private PanelBiblioteca panelBiblioteca = new PanelBiblioteca();
    private PanelPrincipal panelPrincipal = new PanelPrincipal();
    private PanelUsuario panelUsuario = new PanelUsuario();
    private PanelLogo panelLogo = new PanelLogo();

    public InterfazPrincipal() {
        initComponents();
        nuevoPanel1(panelPrincipal);
        nuevoPanel2(panelLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblimagen1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu inicial");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(260, 500));
        jPanel1.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 310));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        lblimagen1.setBackground(new java.awt.Color(255, 255, 255));
        lblimagen1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblimagen1, "card2");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("src/main/java/RECURSOS/SEAUNALENOLOGO.jpg"))); // NOI18N
        jPanel2.add(jLabel1, "card3");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 300, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AbrirLinks(String str) {
        if (java.awt.Desktop.isDesktopSupported()) {
            Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    java.net.URI url = new java.net.URI(str);
                    desktop.browse(url);
                } catch (Exception e) {
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);

            }
        });
    }

    public void nuevoPanel1(JPanel panelActual) {
        jPanel1.removeAll();
        jPanel1.add(panelActual);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    public void nuevoPanel2(JPanel panelActual) {
        jPanel2.removeAll();
        jPanel2.add(panelActual);
        jPanel2.repaint();
        jPanel2.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblimagen1;
    // End of variables declaration//GEN-END:variables

    public class PanelPrincipal extends javax.swing.JPanel {
        final static int NumAleatorios = 1000;

        /**
         * Creates new form PanelPrincipal
         */
        public PanelPrincipal() {
            initComponents();
            double[] data1 = new double[NumAleatorios];

            Stack<Double> datos = llenarVector();
            for (int i = 0; i < NumAleatorios; i++) {
                data1[i] = (double) datos.pop();
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            labelTitulo = new javax.swing.JLabel();
            Busuario1 = new javax.swing.JButton();
            Bbiblioteca1 = new javax.swing.JButton();
            Bprueva1 = new javax.swing.JButton();
            BinformacionPrueba1 = new javax.swing.JButton();
            Bestadisticas = new javax.swing.JButton();

            setBackground(new java.awt.Color(0, 204, 0));

            labelTitulo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
            labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
            labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelTitulo.setText("SEA UNALEÑO");

            Busuario1.setBackground(new java.awt.Color(255, 255, 255));
            Busuario1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Busuario1.setForeground(new java.awt.Color(6, 40, 61));
            Busuario1.setText("PERFIL DEL USUARIO");
            Busuario1.setToolTipText("");
            Busuario1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
                    java.awt.Color.white, java.awt.Color.white));
            Busuario1.setBorderPainted(false);
            Busuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            Busuario1.setMargin(new java.awt.Insets(0, 0, 0, 0));
            Busuario1.setName(""); // NOI18N
            Busuario1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Busuario1ActionPerformed(evt);
                }
            });

            Bbiblioteca1.setBackground(new java.awt.Color(255, 255, 255));
            Bbiblioteca1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bbiblioteca1.setForeground(new java.awt.Color(6, 40, 61));
            Bbiblioteca1.setText("BIBLIOTECA");
            Bbiblioteca1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bbiblioteca1.setBorderPainted(false);
            Bbiblioteca1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bbiblioteca1ActionPerformed(evt);
                }
            });

            Bprueva1.setBackground(new java.awt.Color(255, 255, 255));
            Bprueva1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bprueva1.setForeground(new java.awt.Color(6, 40, 61));
            Bprueva1.setText("PRUEBA");
            Bprueva1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bprueva1.setBorderPainted(false);
            Bprueva1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bprueva1ActionPerformed(evt);
                }
            });

            BinformacionPrueba1.setBackground(new java.awt.Color(255, 255, 255));
            BinformacionPrueba1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            BinformacionPrueba1.setForeground(new java.awt.Color(6, 40, 61));
            BinformacionPrueba1.setText("INFORMACION PRUEBA");
            BinformacionPrueba1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            BinformacionPrueba1.setBorderPainted(false);
            BinformacionPrueba1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BinformacionPrueva1ActionPerformed(evt);
                }
            });

            Bestadisticas.setBackground(new java.awt.Color(255, 255, 255));
            Bestadisticas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bestadisticas.setForeground(new java.awt.Color(6, 40, 61));
            Bestadisticas.setText("ESTADÍSTICAS");
            Bestadisticas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bestadisticas.setBorderPainted(false);
            Bestadisticas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BestadisticasActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bestadisticas, javax.swing.GroupLayout.Alignment.TRAILING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                            .addComponent(BinformacionPrueba1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    228, Short.MAX_VALUE)
                                            .addComponent(Bprueva1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Busuario1, javax.swing.GroupLayout.Alignment.CENTER,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Bbiblioteca1, javax.swing.GroupLayout.Alignment.CENTER,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(50, Short.MAX_VALUE)
                                    .addComponent(Busuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Bbiblioteca1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Bprueva1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BinformacionPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Bestadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(11, Short.MAX_VALUE)
                                            .addComponent(labelTitulo)
                                            .addContainerGap(271, Short.MAX_VALUE))));
        }// </editor-fold>

        private void Busuario1ActionPerformed(java.awt.event.ActionEvent evt) {
            nuevoPanel2(panelUsuario);
        }

        private void Bbiblioteca1ActionPerformed(java.awt.event.ActionEvent evt) {
            nuevoPanel1(panelBiblioteca);
            setTitle("Biblioteca");
        }

        private void Bprueva1ActionPerformed(java.awt.event.ActionEvent evt) {
            HojaRespuestas ventana = new HojaRespuestas();
            ventana.setVisible(true);
            dispose();
        }

        private void BinformacionPrueva1ActionPerformed(java.awt.event.ActionEvent evt) {
            AbrirLinks("https://admisiones.unal.edu.co/pregrado/");
        }

        private void BestadisticasActionPerformed(java.awt.event.ActionEvent evt) {
            double[] data1 = new double[NumAleatorios];

            Stack<Double> datos = llenarVector();
            for (int i = 0; i < NumAleatorios; i++) {
                data1[i] = (double) datos.pop();
            }
            try {
                generarArchivoJSON(data1, "src\\main\\java\\RECURSOS\\data.json");
                ProcessBuilder processBuilder = new ProcessBuilder("python", "src\\main\\java\\PRUEBAS\\graficador.py");

                // Iniciar el proceso y esperar a que finalice
                Process process = processBuilder.start();
                int exitCode = process.waitFor();

                if (exitCode == 0) {
                    System.out.println("Gráfico generado.");
                } else {
                    System.out.println("Error al generar el gráfico.");
                }
            } catch (IOException | InterruptedException ex) {
                ex.printStackTrace();
            }
        }

        public double RandomDouble() {
            Random random = new Random();
            double randomDouble = random.nextDouble();
            // Multiplicamos por 999 para tener un rango de 0 a 999
            randomDouble *= 999;
            // Sumamos 1 para tener un rango de 1 a 1000
            randomDouble += 1;
            // Redondeamos al entero más cercano
            long rounded = Math.round(randomDouble * 1000);
            // Dividimos entre 1000 para tener 3 decimales
            double finalDouble = ((double) rounded) / 1000;
            return finalDouble;
        }

        public void generarArchivoJSON(double[] datos, String nombreArchivo) {
            JSONArray jsonArray = new JSONArray();
            for (double dato : datos) {
                jsonArray.add(dato);
            }

            try (FileWriter fileWriter = new FileWriter(nombreArchivo)) {
                fileWriter.write(jsonArray.toJSONString());
                System.out.println("Archivo JSON generado exitosamente.");
            } catch (IOException e) {
                System.out.println("Error al generar el archivo JSON: " + e.getMessage());
            }
        }

        public Stack<Double> llenarVector() {
            Stack<Double> examenesCalificados = new Stack<Double>(NumAleatorios + 1);
            for (int i = 0; i < NumAleatorios; i++) {
                double Rnd = RandomDouble();
                examenesCalificados.push(Rnd);
            }
            long tiempoInicial = System.nanoTime();
            examenesCalificados.push(RandomDouble());
            System.out.println("s" + NumAleatorios + "=" + (System.nanoTime() - tiempoInicial));
            return examenesCalificados;
        }

        // Variables declaration - do not modify
        private javax.swing.JButton Bbiblioteca1;
        private javax.swing.JButton Bestadisticas;
        private javax.swing.JButton BinformacionPrueba1;
        private javax.swing.JButton Bprueva1;
        private javax.swing.JButton Busuario1;
        private javax.swing.JLabel labelTitulo;
        // End of variables declaration
    }

    public class PanelBiblioteca extends javax.swing.JPanel {

        /**
         * Creates new form PanelBiblioteca
         */
        public PanelBiblioteca() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            lblBiblioteca1 = new javax.swing.JLabel();
            Bmaterial1 = new javax.swing.JButton();
            Bpruebas1 = new javax.swing.JButton();
            Bsolucionarios1 = new javax.swing.JButton();
            Bvolver1 = new javax.swing.JButton();

            setBackground(new java.awt.Color(19, 99, 223));

            lblBiblioteca1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
            lblBiblioteca1.setForeground(new java.awt.Color(255, 255, 255));
            lblBiblioteca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblBiblioteca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("src/main/java/RECURSOS/LIBRO.png"))); // NOI18N
            lblBiblioteca1.setText("BIBLIOTECA");

            Bmaterial1.setBackground(new java.awt.Color(255, 255, 255));
            Bmaterial1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bmaterial1.setForeground(new java.awt.Color(6, 40, 61));
            Bmaterial1.setText("MATERIAL ORGANIZADO");
            Bmaterial1.setToolTipText("");
            Bmaterial1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
                    java.awt.Color.white, java.awt.Color.white));
            Bmaterial1.setBorderPainted(false);
            Bmaterial1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            Bmaterial1.setMargin(new java.awt.Insets(0, 0, 0, 0));
            Bmaterial1.setName(""); // NOI18N
            Bmaterial1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bmaterial1ActionPerformed(evt);
                }
            });

            Bpruebas1.setBackground(new java.awt.Color(255, 255, 255));
            Bpruebas1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bpruebas1.setForeground(new java.awt.Color(6, 40, 61));
            Bpruebas1.setText("PRUEBAS PDF");
            Bpruebas1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bpruebas1.setBorderPainted(false);
            Bpruebas1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bpruebas1ActionPerformed(evt);
                }
            });

            Bsolucionarios1.setBackground(new java.awt.Color(255, 255, 255));
            Bsolucionarios1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bsolucionarios1.setForeground(new java.awt.Color(6, 40, 61));
            Bsolucionarios1.setText("SOLUCIONARIOS");
            Bsolucionarios1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bsolucionarios1.setBorderPainted(false);
            Bsolucionarios1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bsolucionarios1ActionPerformed(evt);
                }
            });

            Bvolver1.setBackground(new java.awt.Color(255, 255, 255));
            Bvolver1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
            Bvolver1.setForeground(new java.awt.Color(6, 40, 61));
            Bvolver1.setText("VOLVER");
            Bvolver1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            Bvolver1.setBorderPainted(false);
            Bvolver1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bvolver1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 240, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout
                                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblBiblioteca1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Bmaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 228,
                                                            Short.MAX_VALUE)
                                                    .addComponent(Bpruebas1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Bsolucionarios1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Bvolver1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addContainerGap())));
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 315, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(lblBiblioteca1)
                                            .addGap(18, 18, 18)
                                            .addComponent(Bmaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Bpruebas1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Bsolucionarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Bvolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(34, Short.MAX_VALUE))));
        }// </editor-fold>

        private void Bmaterial1ActionPerformed(java.awt.event.ActionEvent evt) {
            AbrirLinks("https://drive.google.com/drive/folders/1g4cdM7H9F96k5hvfk6hhfZVCP8jZWNri?usp=share_link");
        }

        private void Bpruebas1ActionPerformed(java.awt.event.ActionEvent evt) {
            AbrirLinks("https://drive.google.com/drive/folders/1qyUZa2epX3e3pNVD8S7QkHFgg0AgfHZb?usp=share_link");
        }

        private void Bsolucionarios1ActionPerformed(java.awt.event.ActionEvent evt) {
            AbrirLinks("https://drive.google.com/drive/folders/19izxlswEJaJZTV-V2mJ0k9Mwh1gYUool?usp=share_link");
        }

        private void Bvolver1ActionPerformed(java.awt.event.ActionEvent evt) {
            nuevoPanel1(panelPrincipal);
            nuevoPanel2(panelLogo);
            setTitle("Menu inicial");
        }

        public void AbrirLinks(String str) {
            if (java.awt.Desktop.isDesktopSupported()) {
                Desktop desktop = java.awt.Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    try {
                        java.net.URI url = new java.net.URI(str);
                        desktop.browse(url);
                    } catch (Exception e) {
                    }
                }
            }
        }

        // Variables declaration - do not modify
        private javax.swing.JButton Bmaterial1;
        private javax.swing.JButton Bpruebas1;
        private javax.swing.JButton Bsolucionarios1;
        private javax.swing.JButton Bvolver1;
        private javax.swing.JLabel lblBiblioteca1;
        // End of variables declaration
    }
}
